# File to edit: backend/volunteers/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    VolunteerViewSet,
    RunningSessionViewSet,
    EmailCheckView,
    SessionLabelUpdateView
)

# The router and all app-specific URLs are defined here.
router = DefaultRouter()
router.register(r'volunteers', VolunteerViewSet, basename='volunteer')
router.register(r'sessions', RunningSessionViewSet, basename='session')

# The API URLs are a combination of the router's URLs and any custom paths.
urlpatterns = [
    # Custom path for checking email
    path('check-email/', EmailCheckView.as_view(), name='check-email'),
    
    # This is the correct path that your frontend is trying to reach.
    # It will now be properly exposed via the include in core/urls.py.
    path('sessions/<int:pk>/update-label/', SessionLabelUpdateView.as_view(), name='session-update-label'),
    
    # Include all the URLs automatically generated by the router
    # This will create paths like /sessions/ and /sessions/<pk>/
    path('', include(router.urls)),
]