# File to edit: backend/volunteers/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    VolunteerViewSet,
    RunningSessionViewSet,
    EmailCheckView,
    SessionLabelUpdateView
    # The incorrect import of 'update_session_anomalies' has been removed
)

# The router and all app-specific URLs are defined here.
router = DefaultRouter()
router.register(r'volunteers', VolunteerViewSet, basename='volunteer')
router.register(r'sessions', RunningSessionViewSet, basename='session')

# The API URLs are a combination of the router's URLs and any custom paths.
urlpatterns = [
    # Custom path for checking email
    path('check-email/', EmailCheckView.as_view(), name='check-email'),
    
    # This path is for updating the overall session label
    path('sessions/<int:pk>/update-label/', SessionLabelUpdateView.as_view(), name='session-update-label'),
    
    # The path for 'update-anomalies' is now created automatically by the router
    # because of the @action in your ViewSet, so the manual path has been removed.
    
    # Include all the URLs automatically generated by the router
    path('', include(router.urls)),
]