from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    VolunteerViewSet,
    RunningSessionViewSet,
    EmailCheckView,
    SessionLabelUpdateView
)

# Create a router and register our viewsets with it.
# The router automatically generates URL patterns for ViewSets.
# e.g., /volunteers/, /volunteers/{pk}/, /sessions/, /sessions/{pk}/
router = DefaultRouter()
router.register(r'volunteers', VolunteerViewSet, basename='volunteer')
router.register(r'sessions', RunningSessionViewSet, basename='session')

# The API URLs are a combination of the router's URLs and any custom paths.
urlpatterns = [
    # Custom paths for specific, non-ViewSet actions
    path('check-email/', EmailCheckView.as_view(), name='check-email'),
    path('sessions/<int:pk>/update-label/', SessionLabelUpdateView.as_view(), name='session-update-label'),
    
    # Include all the URLs automatically generated by the router
    path('', include(router.urls)),
]