# Generated by Django 5.2.3 on 2025-06-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150, unique=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(max_length=20)),
                ("nationality", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("platform", models.CharField(max_length=100)),
                ("smartwatch", models.CharField(max_length=100)),
                ("run_frequency", models.CharField(max_length=100)),
                ("consent_acknowledged", models.BooleanField(default=False)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
