# Generated by Django 5.2.3 on 2025-07-06 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0002_volunteer_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateTimeField()),
                (
                    "source_type",
                    models.CharField(
                        help_text="e.g., 'admin_upload', 'strava_api'", max_length=50
                    ),
                ),
                ("timeseries_data", models.JSONField(blank=True, null=True)),
                (
                    "ml_prediction",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ml_confidence", models.FloatField(blank=True, null=True)),
                (
                    "admin_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="volunteers.volunteer",
                    ),
                ),
            ],
        ),
    ]
