# Generated by Django 5.2.3 on 2025-07-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0003_runningsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="runningsession",
            name="session_file",
            field=models.FileField(blank=True, null=True, upload_to="session_files/"),
        ),
    ]
