# Generated by Django 5.2.3 on 2025-07-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0004_runningsession_session_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runningsession",
            name="source_type",
            field=models.CharField(help_text="e.g., 'admin_upload'", max_length=50),
        ),
    ]
