# Generated by Django 5.2.3 on 2025-07-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0005_alter_runningsession_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="runningsession",
            name="avg_heart_rate",
            field=models.IntegerField(
                blank=True, help_text="Average heart rate in bpm", null=True
            ),
        ),
        migrations.AddField(
            model_name="runningsession",
            name="max_heart_rate",
            field=models.IntegerField(
                blank=True, help_text="Maximum heart rate in bpm", null=True
            ),
        ),
        migrations.AddField(
            model_name="runningsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="processing",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="runningsession",
            name="total_distance_km",
            field=models.FloatField(
                blank=True, help_text="Total distance in kilometers", null=True
            ),
        ),
        migrations.AddField(
            model_name="runningsession",
            name="total_duration_secs",
            field=models.FloatField(
                blank=True, help_text="Total duration in seconds", null=True
            ),
        ),
        migrations.AlterField(
            model_name="runningsession",
            name="timeseries_data",
            field=models.JSONField(
                blank=True,
                help_text="Stores the full time-series data from the file",
                null=True,
            ),
        ),
    ]
