# Generated by Django 5.2.3 on 2025-07-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0006_runningsession_avg_heart_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="runningsession",
            name="processing_error",
            field=models.TextField(
                blank=True,
                help_text="Stores the error message if processing fails",
                null=True,
            ),
        ),
    ]
