from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from volunteers import views

router = DefaultRouter()
router.register(r'volunteers', views.VolunteerViewSet, basename='volunteer')

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Use our new custom login view for authentication
    path('api-auth/login/', views.CustomLoginView.as_view(), name='api_token_auth'),
    
    # Include all the URLs automatically generated by the router for volunteers
    path('api/', include(router.urls)),
]